-- DEBUG LOG TABLE
-- =========================================

CREATE TABLE debug_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name VARCHAR2(100),
    line_no NUMBER,
    log_message VARCHAR2(4000),
    session_id VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

SELECT * FROM debug_log

-- EMPLOYEES TABLE
-- =========================================
CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    salary NUMBER(10,2) NOT NULL,
    commission_pct NUMBER(5,2)
);
/

-- SAMPLE DATA FOR EMPLOYEES
-- =========================================
INSERT INTO employees (employee_id, first_name, last_name, salary, commission_pct)
VALUES (1, 'Ana', 'Popescu', 5000, 0.10);

INSERT INTO employees (employee_id, first_name, last_name, salary, commission_pct)
VALUES (2, 'Mihai', 'Ionescu', 6000, NULL);

INSERT INTO employees (employee_id, first_name, last_name, salary, commission_pct)
VALUES (3, 'Elena', 'Georgescu', 4500, 0.15);

COMMIT;

SELECT *
FROM employees;

-- =========================================
-- PACKAGE SPECIFICATION: DEBUG_UTILS
-- =========================================

CREATE OR REPLACE PACKAGE debug_utils AS
    g_debug_mode BOOLEAN := FALSE;

    PROCEDURE enable_debug;
    PROCEDURE disable_debug;

    PROCEDURE log_msg(
        p_module_name VARCHAR2,
        p_line NUMBER,
        p_message VARCHAR2
    );

    PROCEDURE log_variable(
        p_module_name VARCHAR2,
        p_line NUMBER,
        p_name VARCHAR2,
        p_value VARCHAR2
    );

    PROCEDURE log_error(
        p_module_name VARCHAR2,
        p_line NUMBER,
        p_err VARCHAR2
    );
END debug_utils;
/