CREATE TABLE dim_employee (
    id NUMBER PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    salary NUMBER
);

CREATE TABLE dim_project (
    id NUMBER PRIMARY KEY,
    project_name VARCHAR2(50)
);

CREATE TABLE dim_time (
    id NUMBER PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,
    day_name VARCHAR2(10),
    week_start DATE,
    week_end DATE,
    quarter NUMBER
);

CREATE TABLE dim_event (
    id NUMBER PRIMARY KEY,
    event_name VARCHAR2(100)
);

CREATE TABLE fact_pontaj (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    project_id NUMBER,
    time_id NUMBER,
    event_id NUMBER,
    hours_worked NUMBER,
    
    FOREIGN KEY (employee_id) REFERENCES dim_employee(id),
    FOREIGN KEY (project_id) REFERENCES dim_project(id),
    FOREIGN KEY (time_id) REFERENCES dim_time(id),
    FOREIGN KEY (event_id) REFERENCES dim_event(id)
);